[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["--cov=wandb_osh", "-ra", "--showlocals", "--strict-markers", "--strict-config", "--cov-branch"]
xfail_strict = true

[tool.ruff.isort]
required-imports = ["from __future__ import annotations"]

[tool.ruff]
ignore-init-module-imports = true

[tool.pycln]
all = true
